// Sample accommodations for testing the booking system
import { AccommodationDetail } from "@/types";

export const sampleAccommodations: AccommodationDetail[] = [
    {
        id: "grand-seoul-hotel",
        title: "Grand Seoul Luxury Hotel",
        location: "Seoul, Gangnam-gu",
        address: "123 Teheran-ro, Gangnam-gu, Seoul, South Korea 06234",
        rating: 4.8,
        reviewCount: 1547,
        description:
            "Experience unparalleled luxury in the heart of Seoul's vibrant Gangnam district. Grand Seoul Luxury Hotel offers stunning city views, world-class amenities, and exceptional service. Our hotel features modern architecture with traditional Korean aesthetics, creating a unique blend of comfort and culture. Located just minutes from COEX Mall, K-Star Road, and major business centers, we're the perfect choice for both leisure and business travelers. Each room is meticulously designed with premium bedding, state-of-the-art technology, and elegant furnishings to ensure your stay is memorable.",
        images: [
            "https://images.unsplash.com/photo-1566073771259-6a8506099945?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&h=800&fit=crop",
        ],
        priceRange: "280,000원 - 850,000원",
        checkInTime: "15:00",
        checkOutTime: "11:00",
        amenities: [
            {
                id: "wifi",
                name: "Free High-Speed WiFi",
                icon: "Wifi",
                category: "Internet",
            },
            {
                id: "parking",
                name: "Valet Parking",
                icon: "Car",
                category: "Parking",
            },
            {
                id: "restaurant",
                name: "Fine Dining Restaurant",
                icon: "Utensils",
                category: "Dining",
            },
            {
                id: "gym",
                name: "24/7 Fitness Center",
                icon: "Dumbbell",
                category: "Fitness",
            },
            {
                id: "pool",
                name: "Infinity Pool",
                icon: "Waves",
                category: "Recreation",
            },
            {
                id: "spa",
                name: "Luxury Spa",
                icon: "Bell",
                category: "Wellness",
            },
            {
                id: "concierge",
                name: "24/7 Concierge",
                icon: "User",
                category: "Service",
            },
            {
                id: "breakfast",
                name: "Breakfast Buffet",
                icon: "Coffee",
                category: "Dining",
            },
        ],
        rooms: [
            {
                id: "deluxe-double",
                name: "Deluxe Double Room",
                description:
                    "Elegant 32㎡ room with city views, king-size bed, and modern amenities. Perfect for couples or solo travelers seeking comfort and style.",
                images: [
                    "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 2,
                },
                bedType: "1 King Bed",
                size: 32,
                price: "280,000원",
                originalPrice: "350,000원",
                discount: "20%",
                checkInTime: "15:00",
                checkOutTime: "11:00",
                amenities: [
                    "Free WiFi",
                    "55\" Smart TV",
                    "Mini Bar",
                    "Coffee Maker",
                    "Safe",
                    "Air Conditioning",
                    "Blackout Curtains",
                    "Premium Toiletries",
                ],
                availability: "available",
                remainingRooms: 8,
                cancellationPolicy: "Free cancellation up to 24 hours before check-in",
            },
            {
                id: "executive-suite",
                name: "Executive Suite",
                description:
                    "Spacious 58㎡ suite with separate living area, stunning panoramic views, and premium amenities. Ideal for extended stays or business travelers.",
                images: [
                    "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 3,
                },
                bedType: "1 King Bed + Sofa Bed",
                size: 58,
                price: "520,000원",
                originalPrice: "680,000원",
                discount: "24%",
                checkInTime: "15:00",
                checkOutTime: "11:00",
                amenities: [
                    "Free WiFi",
                    "65\" Smart TV",
                    "Mini Bar",
                    "Nespresso Machine",
                    "Safe",
                    "Air Conditioning",
                    "Work Desk",
                    "Premium Toiletries",
                    "Bathrobes & Slippers",
                    "Executive Lounge Access",
                ],
                availability: "available",
                remainingRooms: 3,
                cancellationPolicy: "Free cancellation up to 48 hours before check-in",
            },
            {
                id: "presidential-suite",
                name: "Presidential Suite",
                description:
                    "Ultimate luxury in our 95㎡ presidential suite. Features panoramic city views, separate bedroom, living room, dining area, and exclusive butler service.",
                images: [
                    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 4,
                },
                bedType: "1 King Bed + 2 Single Beds",
                size: 95,
                price: "850,000원",
                checkInTime: "14:00",
                checkOutTime: "12:00",
                amenities: [
                    "Free WiFi",
                    "75\" Smart TV",
                    "Full Bar",
                    "Nespresso Machine",
                    "Safe",
                    "Air Conditioning",
                    "Work Desk",
                    "Premium Toiletries",
                    "Bathrobes & Slippers",
                    "Butler Service",
                    "Private Balcony",
                    "Jacuzzi",
                ],
                availability: "limited",
                remainingRooms: 1,
                cancellationPolicy: "Free cancellation up to 72 hours before check-in",
            },
        ],
        reviews: [
            {
                id: "r1",
                author: "김민준",
                rating: 5,
                date: "2025-09-28",
                comment:
                    "Absolutely perfect stay! The service was impeccable, rooms were stunning, and the location couldn't be better. Will definitely return!",
                helpful: 24,
                images: [
                    "https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=400&h=300&fit=crop",
                ],
            },
            {
                id: "r2",
                author: "Sarah Johnson",
                rating: 5,
                date: "2025-09-15",
                comment:
                    "Best hotel experience in Seoul! The Executive Suite was spacious and luxurious. Staff went above and beyond to make our anniversary special.",
                helpful: 18,
            },
            {
                id: "r3",
                author: "박서연",
                rating: 4,
                date: "2025-09-10",
                comment:
                    "Great hotel with excellent amenities. The infinity pool has amazing views. Only minor complaint is breakfast could have more variety.",
                helpful: 12,
            },
        ],
        aiReviewSummary:
            "Guests consistently praise the exceptional service, luxurious rooms, and prime location. The infinity pool and spa facilities are highly rated. Some guests note that breakfast variety could be improved. Overall satisfaction: 96%.",
        badges: [
            "Luxury Hotel",
            "Business Friendly",
            "Best Location",
            "Top Rated 2025",
        ],
        policies: {
            cancellation:
                "Free cancellation up to 24-72 hours before check-in (varies by room type). Late cancellations or no-shows will be charged the full amount.",
            children:
                "Children of all ages are welcome. Children under 12 stay free when using existing beds.",
            pets: "Pets are not allowed.",
            smoking: "This is a non-smoking property. Designated smoking areas available.",
        },
        nearbyAttractions: [
            "COEX Mall - 800m",
            "Bongeunsa Temple - 1.2km",
            "Samsung Station - 500m",
            "K-Star Road - 1.5km",
        ],
    },
    {
        id: "jeju-ocean-resort",
        title: "Jeju Ocean View Resort & Spa",
        location: "Jeju Island, Seogwipo",
        address: "456 Coastal Road, Seogwipo-si, Jeju-do, South Korea 63594",
        rating: 4.9,
        reviewCount: 2341,
        description:
            "Discover paradise at Jeju Ocean View Resort & Spa, where pristine beaches meet luxury accommodation. Nestled along Jeju Island's stunning southern coast, our resort offers breathtaking ocean views, private beach access, and world-class spa facilities. Each room features floor-to-ceiling windows showcasing the emerald waters and volcanic landscape. Indulge in authentic Jeju cuisine at our restaurants, unwind at our traditional Korean spa, or explore nearby natural wonders including waterfalls and lava tubes. Perfect for romantic getaways, family vacations, and wellness retreats.",
        images: [
            "https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1573052905904-34ad8c27f0cc?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1584132967334-10e028bd69f7?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1540541338287-41700207dee6?w=1200&h=800&fit=crop",
        ],
        priceRange: "180,000원 - 650,000원",
        checkInTime: "15:00",
        checkOutTime: "11:00",
        amenities: [
            {
                id: "wifi",
                name: "Free High-Speed WiFi",
                icon: "Wifi",
                category: "Internet",
            },
            {
                id: "parking",
                name: "Free Parking",
                icon: "Car",
                category: "Parking",
            },
            {
                id: "restaurant",
                name: "3 Restaurants & Bar",
                icon: "Utensils",
                category: "Dining",
            },
            {
                id: "gym",
                name: "Fitness Center",
                icon: "Dumbbell",
                category: "Fitness",
            },
            {
                id: "pool",
                name: "Outdoor Pool",
                icon: "Waves",
                category: "Recreation",
            },
            {
                id: "spa",
                name: "Korean Spa & Sauna",
                icon: "Bell",
                category: "Wellness",
            },
            {
                id: "beach",
                name: "Private Beach Access",
                icon: "Waves",
                category: "Recreation",
            },
            {
                id: "breakfast",
                name: "Breakfast Buffet",
                icon: "Coffee",
                category: "Dining",
            },
        ],
        rooms: [
            {
                id: "ocean-view-double",
                name: "Ocean View Double Room",
                description:
                    "Bright and airy 38㎡ room with spectacular ocean views, private balcony, and modern amenities. Wake up to the sound of waves and stunning sunrises.",
                images: [
                    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1631049035410-c6d6de5e2540?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 3,
                },
                bedType: "1 King Bed or 2 Twin Beds",
                size: 38,
                price: "180,000원",
                originalPrice: "240,000원",
                discount: "25%",
                checkInTime: "15:00",
                checkOutTime: "11:00",
                amenities: [
                    "Free WiFi",
                    "50\" Smart TV",
                    "Mini Fridge",
                    "Coffee Maker",
                    "Safe",
                    "Air Conditioning",
                    "Private Balcony",
                    "Ocean View",
                ],
                availability: "available",
                remainingRooms: 12,
                cancellationPolicy: "Free cancellation up to 24 hours before check-in",
            },
            {
                id: "family-suite-beach",
                name: "Family Beach Suite",
                description:
                    "Spacious 62㎡ family suite with two bedrooms, ocean views, and direct beach access. Perfect for families seeking comfort and convenience.",
                images: [
                    "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 4,
                    max: 5,
                },
                bedType: "1 King Bed + 2 Single Beds",
                size: 62,
                price: "380,000원",
                originalPrice: "480,000원",
                discount: "21%",
                checkInTime: "15:00",
                checkOutTime: "11:00",
                amenities: [
                    "Free WiFi",
                    "2x 50\" Smart TV",
                    "Kitchenette",
                    "Coffee Maker",
                    "Safe",
                    "Air Conditioning",
                    "Private Balcony",
                    "Ocean View",
                    "Kids Amenities",
                    "Beach Toys",
                ],
                packages: [
                    {
                        id: "family-fun",
                        name: "Family Fun Package",
                        description:
                            "Includes breakfast buffet for 4, water park tickets, and kids activities",
                        price: "480,000원",
                        originalPrice: "580,000원",
                        discount: "17%",
                        benefits: [
                            "Breakfast for 4",
                            "Water Park Access",
                            "Kids Club Activities",
                            "Beach Equipment",
                        ],
                    },
                ],
                availability: "available",
                remainingRooms: 6,
                cancellationPolicy: "Free cancellation up to 48 hours before check-in",
            },
            {
                id: "honeymoon-villa",
                name: "Honeymoon Ocean Villa",
                description:
                    "Romantic 85㎡ private villa with infinity pool, outdoor shower, panoramic ocean views, and exclusive amenities. Perfect for couples seeking privacy and luxury.",
                images: [
                    "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 2,
                },
                bedType: "1 King Bed",
                size: 85,
                price: "650,000원",
                checkInTime: "14:00",
                checkOutTime: "12:00",
                amenities: [
                    "Free WiFi",
                    "65\" Smart TV",
                    "Private Pool",
                    "Outdoor Shower",
                    "Nespresso Machine",
                    "Safe",
                    "Air Conditioning",
                    "Premium Toiletries",
                    "Bathrobes & Slippers",
                    "Champagne on Arrival",
                    "Turn-down Service",
                ],
                packages: [
                    {
                        id: "honeymoon-special",
                        name: "Honeymoon Special",
                        description:
                            "Complete romantic package with spa treatments, private dinner, and more",
                        price: "780,000원",
                        originalPrice: "920,000원",
                        discount: "15%",
                        benefits: [
                            "Couples Spa Treatment",
                            "Private Beach Dinner",
                            "Flower Decoration",
                            "Photo Session",
                            "Late Check-out",
                        ],
                    },
                ],
                availability: "limited",
                remainingRooms: 2,
                cancellationPolicy: "Free cancellation up to 72 hours before check-in",
            },
        ],
        reviews: [
            {
                id: "r1",
                author: "이서현",
                rating: 5,
                date: "2025-09-25",
                comment:
                    "Perfect honeymoon destination! The private villa was absolutely stunning. Waking up to ocean views every morning was magical. Staff was incredibly attentive.",
                helpful: 45,
                images: [
                    "https://images.unsplash.com/photo-1582719508461-905c673771fd?w=400&h=300&fit=crop",
                ],
            },
            {
                id: "r2",
                author: "Michael Chen",
                rating: 5,
                date: "2025-09-18",
                comment:
                    "Best family vacation ever! Kids loved the beach and pool. Rooms were spacious and clean. The breakfast buffet had amazing variety including local Jeju specialties.",
                helpful: 32,
            },
            {
                id: "r3",
                author: "최유진",
                rating: 5,
                date: "2025-09-05",
                comment:
                    "Absolutely breathtaking resort! The Korean spa was incredible and the restaurants served delicious food. Can't wait to come back!",
                helpful: 28,
            },
        ],
        aiReviewSummary:
            "Guests rave about the spectacular ocean views, pristine beach, and exceptional service. The Korean spa and dining options receive outstanding reviews. Families particularly appreciate the spacious suites and kids' facilities. Overall satisfaction: 98%.",
        badges: [
            "Beach Resort",
            "Family Friendly",
            "Spa & Wellness",
            "Romantic Getaway",
        ],
        policies: {
            cancellation:
                "Free cancellation up to 24-72 hours before check-in (varies by room type). Late cancellations or no-shows will be charged the full amount.",
            children:
                "Children of all ages are welcome. Children under 10 stay free when using existing beds. Kids club available for ages 4-12.",
            pets: "Small pets (under 5kg) allowed in select rooms with advance notice. Pet fee: 30,000원/night.",
            smoking:
                "This is a non-smoking property. Designated outdoor smoking areas available.",
        },
        nearbyAttractions: [
            "Jeongbang Waterfall - 3.2km",
            "Cheonjiyeon Waterfall - 4.5km",
            "Oedolgae Rock - 2.8km",
            "Seogwipo Maeil Olle Market - 5.1km",
        ],
    },
    {
        id: "busan-business-hotel",
        title: "Busan Central Business Hotel",
        location: "Busan, Haeundae-gu",
        address: "789 Marine City Road, Haeundae-gu, Busan, South Korea 48099",
        rating: 4.7,
        reviewCount: 1856,
        description:
            "Strategically located in Busan's premier business district, Busan Central Business Hotel offers the perfect blend of convenience and comfort for business and leisure travelers. Our hotel features state-of-the-art meeting facilities, high-speed internet throughout, and executive services designed for the modern professional. Just steps from Haeundae Beach and the BEXCO convention center, we provide easy access to both business venues and recreational attractions. Each room is equipped with ergonomic workspaces, premium amenities, and stunning views of either the ocean or the city skyline.",
        images: [
            "https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=1200&h=800&fit=crop",
            "https://images.unsplash.com/photo-1566195992011-5f6b21e539aa?w=1200&h=800&fit=crop",
        ],
        priceRange: "150,000원 - 420,000원",
        checkInTime: "14:00",
        checkOutTime: "12:00",
        amenities: [
            {
                id: "wifi",
                name: "Free High-Speed WiFi",
                icon: "Wifi",
                category: "Internet",
            },
            {
                id: "parking",
                name: "Underground Parking",
                icon: "Car",
                category: "Parking",
            },
            {
                id: "restaurant",
                name: "Restaurant & Cafe",
                icon: "Utensils",
                category: "Dining",
            },
            {
                id: "gym",
                name: "Fitness Center",
                icon: "Dumbbell",
                category: "Fitness",
            },
            {
                id: "business",
                name: "Business Center",
                icon: "User",
                category: "Business",
            },
            {
                id: "lounge",
                name: "Executive Lounge",
                icon: "Coffee",
                category: "Service",
            },
            {
                id: "meeting",
                name: "Meeting Rooms",
                icon: "User",
                category: "Business",
            },
            {
                id: "breakfast",
                name: "Breakfast",
                icon: "Coffee",
                category: "Dining",
            },
        ],
        rooms: [
            {
                id: "superior-room",
                name: "Superior Business Room",
                description:
                    "Comfortable 28㎡ room designed for business travelers. Features ergonomic work desk, high-speed internet, and modern amenities for a productive stay.",
                images: [
                    "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 2,
                },
                bedType: "1 Queen Bed",
                size: 28,
                price: "150,000원",
                originalPrice: "190,000원",
                discount: "21%",
                checkInTime: "14:00",
                checkOutTime: "12:00",
                amenities: [
                    "Free WiFi",
                    "48\" Smart TV",
                    "Work Desk",
                    "Coffee Maker",
                    "Safe",
                    "Air Conditioning",
                    "Iron & Board",
                    "Hair Dryer",
                ],
                availability: "available",
                remainingRooms: 15,
                cancellationPolicy: "Free cancellation up to 18:00 on check-in day",
            },
            {
                id: "executive-ocean",
                name: "Executive Ocean View",
                description:
                    "Premium 42㎡ room with stunning Haeundae Beach views. Includes executive lounge access and enhanced business amenities for discerning travelers.",
                images: [
                    "https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 3,
                },
                bedType: "1 King Bed",
                size: 42,
                price: "280,000원",
                originalPrice: "350,000원",
                discount: "20%",
                checkInTime: "14:00",
                checkOutTime: "12:00",
                amenities: [
                    "Free WiFi",
                    "55\" Smart TV",
                    "Work Desk",
                    "Nespresso Machine",
                    "Safe",
                    "Air Conditioning",
                    "Ocean View",
                    "Executive Lounge Access",
                    "Free Pressing",
                    "Premium Toiletries",
                ],
                availability: "available",
                remainingRooms: 7,
                cancellationPolicy: "Free cancellation up to 24 hours before check-in",
            },
            {
                id: "business-suite",
                name: "Business Suite",
                description:
                    "Spacious 55㎡ suite with separate living and working areas. Perfect for extended stays or conducting private meetings. Includes all executive amenities.",
                images: [
                    "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&h=600&fit=crop",
                    "https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&h=600&fit=crop",
                ],
                capacity: {
                    standard: 2,
                    max: 4,
                },
                bedType: "1 King Bed + Sofa Bed",
                size: 55,
                price: "420,000원",
                checkInTime: "14:00",
                checkOutTime: "13:00",
                amenities: [
                    "Free WiFi",
                    "2x 55\" Smart TV",
                    "Large Work Desk",
                    "Meeting Table",
                    "Nespresso Machine",
                    "Safe",
                    "Air Conditioning",
                    "Executive Lounge Access",
                    "Free Laundry",
                    "Premium Toiletries",
                    "Printer/Scanner Access",
                ],
                availability: "available",
                remainingRooms: 4,
                cancellationPolicy: "Free cancellation up to 48 hours before check-in",
            },
        ],
        reviews: [
            {
                id: "r1",
                author: "James Park",
                rating: 5,
                date: "2025-09-20",
                comment:
                    "Perfect for business trips! Location is excellent - close to BEXCO and the beach. Fast WiFi, comfortable workspace, and the executive lounge was a great perk.",
                helpful: 19,
            },
            {
                id: "r2",
                author: "김지훈",
                rating: 5,
                date: "2025-09-12",
                comment:
                    "Excellent hotel for both work and leisure. The room was modern and clean. Beach view from executive room was stunning. Great breakfast buffet!",
                helpful: 15,
            },
            {
                id: "r3",
                author: "Emma Wilson",
                rating: 4,
                date: "2025-08-30",
                comment:
                    "Great business hotel with all needed amenities. Meeting rooms were well-equipped. Only minor issue was parking can get busy during peak hours.",
                helpful: 11,
            },
        ],
        aiReviewSummary:
            "Business travelers highly praise the convenient location near BEXCO, excellent WiFi, and professional service. Leisure guests appreciate the proximity to Haeundae Beach. Executive lounge and meeting facilities receive consistent positive feedback. Overall satisfaction: 94%.",
        badges: [
            "Business Hotel",
            "Beach Location",
            "Convention Center Access",
            "Executive Friendly",
        ],
        policies: {
            cancellation:
                "Free cancellation up to 18:00-48 hours before check-in (varies by room type). Late cancellations or no-shows will be charged one night's stay.",
            children:
                "Children of all ages are welcome. Children under 8 stay free when using existing beds.",
            pets: "Pets are not allowed.",
            smoking:
                "This is a non-smoking property. Designated smoking area on 5th floor terrace.",
        },
        nearbyAttractions: [
            "Haeundae Beach - 200m",
            "BEXCO Convention Center - 1.5km",
            "Dongbaek Island - 2.1km",
            "The Bay 101 - 2.8km",
        ],
    },
];

